name: 'market_flow'
version: '1.0.0'
config-version: 2
profile: 'market_flow'

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]

target-path: "target"
log-path: "logs"
clean-targets:
  - "target"
  - "dbt_packages"
