FROM python:3.9-slim

ENV PYTHONUNBUFFERED=1

WORKDIR /app

COPY requirements.txt requirements.txt
COPY config.toml config.toml
RUN pip install -r requirements.txt

EXPOSE 8501

CMD ["streamlit", "run", "server/app.py", "--server.port=8501", "--server.address=0.0.0.0"]
