FROM apache/airflow:2.10.3

# Install dbt and its dependencies
RUN pip install dbt-core dbt-postgres dbt-duckdb 

# dependecies related to open-meteo
RUN pip install openmeteo-requests
RUN pip install requests-cache retry-requests numpy pandas
RUN pip install currencyapicom
RUN pip install scikit-learn
RUN pip install "sqlframe[duckdb]"
RUN pip install python-dotenv
RUN pip install ratelimit backoff
