market_flow:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: "/opt/airflow/db/analytics.duckdb"
      schema: raw
      extensions:
        - postgres
        - postgres_scanner

models:
  market_flow:
    raw:
      +materialized: table
      +schema: raw
    staging:
      +materialized: table
      +schema: staging
    analytics:
      +materialized: table
      +schema: analytics

