market_flow:
  target: dev
  outputs:
    dev:
      type: postgres
      host: postgres
      user: airflow
      password: airflow
      dbname: market_flow
      schema: public
      port: 5432
      threads: 4
    duckdb:
      type: duckdb
      path: "/opt/airflow/db/analytics.duckdb"
      schema: analytics 
      extensions:
        - postgres
        - postgres_scanner
      attach:
        - path: postgresql://airflow:airflow@postgres/market_flow
          type: postgres
