version: 2
sources:
  - name: raw
    schema: raw
    tables:
      - name: hdi
        loaded_at_field: _loaded_at
        description: Raw Human Development Index Data
      - name: wfp
        loaded_at_field: _loaded_at
        description: Raw World Food Program Index Data
      - name: coordinates
        loaded_at_field: created_at
        description: Coordinates for each locality
      - name: weather
        loaded_at_field: created_at
        description: weather combination for every coordinate
      - name: currencies_historical
        description: historical value of coin based on USD
