version: 2
sources:
  - name: staging
    schema: staging
    tables:
      - name: stg_transactions
        description: WFP data as transactions
      - name: stg_units
        description: units of each product
      - name: stg_cleaned_units
        description: Cleaned units
      - name: stg_commodities
        description: Commodities list
      - name: stg_countries
        description: Countries list
      - name: stg_currencies
        description: Currencies list
